services:
  db:
    image: pgvector/pgvector:pg16
    container_name: rag-pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ragdb
    ports:
      - "5433:5432"
    volumes:
      - rag_pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: rag-api
    environment:
      PG_DSN: postgresql://postgres:postgres@db:5432/ragdb
      USE_MOCK_LLM: "true"
    depends_on:
      - db
    ports:
      - "5002:5002"

volumes:
  rag_pgdata:
